trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  vmName: 'demo-vm'
  adminUsername: 'azureuser'
  adminPassword: '$(adminPassword)'  # Marked as secret in pipeline

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureConnection'
    subscriptionId: 'bfcf4987-6623-4e35-b4bc-b75dbfb422ae'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevOpsVM-RG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
