name: Deploy Azure VM

on:
  push:
    branches:
      - bicep-vm-cicd
  workflow_dispatch:
    inputs:
      osType:
        description: 'Choose VM operating system'
        required: true
        default: 'Linux'
        type: choice
        options:
          - Linux
          - Windows

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Login to Azure
      uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: az group create --name RG-Test-VimalNeo --location eastus

    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group RG-Test-VimalNeo \
          --template-file ./main.bicep \
          --parameters ./main.parameters.json \
          --parameters osType=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.osType || 'Linux' }}